name: StackStrap
description: Evolving DevOps with Salt, Vagrant and Docker.
meta_description: "Evolving DevOps with Salt, Vagrant and Docker."

markdown: redcarpet
pygments: true
logo: false

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
