name: StackStrap
description: Combining Salt, Vagrant and Docker to evolve DevOps for everyone.
meta_description: "Combining Salt, Vagrant and Docker to evolve DevOps for everyone."

markdown: redcarpet
pygments: true
logo: false

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
